WebAppTest/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppTest.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public virtual List<ProductReview> Reviews { get; set; }
    }
}

WebAppTest/Models/ProductDb.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WebAppTest.Models
{
    public class ProductDb : DbContext
    {
        public ProductDb() : base("name=DefaultConnection")
        {

        }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductReview> Reviews { get; set; }
    }
}

WebAppTest/Models/ProductReview.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAppTest.Models
{
    public class ProductReview
    {
        public int Id { get; set; }
        [Required]
        [StringLength(1024)]
        public string Review { get; set; }
        [Display(Name ="User Name")]
        [DisplayFormat(NullDisplayText ="anonymous")]
        public string ReviewerName { get; set; }
        [Range(1,10)]
        [Required]
        public int Rating { get; set; }
        public int ProductId { get; set; }
    }
}

WebAppTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppTest.Models;
using System.Data.Entity;
using PagedList;

namespace WebAppTest.Controllers
{
    public class HomeController : Controller
    {
        ProductDb _db = new ProductDb();
        public ActionResult Autocomplete(string term)
        {
            var model = _db.Products.Where(p => p.Name.StartsWith(term)).Take(10).Select(r => new { label = r.Name });

            return Json(model, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Index(string searchTerm = null,int page =1)
        {
            var model = _db.Products.OrderByDescending(p => p.Reviews.Average(r => r.Rating)).Where(x=>x.Name.StartsWith(searchTerm)||searchTerm==null).ToPagedList(page,10);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_Products", model);
            }
            return View(model);
        }

        protected override void Dispose(bool disposing)
        {
            if(_db != null)
            {
                _db.Dispose();                
            }
            base.Dispose(disposing);
        }
    }
}

WebAppTest/Controllers/ProductReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppTest.Models;

namespace WebAppTest.Controllers
{
    public class ProductReviewsController : Controller
    {
        private ProductDb db = new ProductDb();

        // GET: ProductReviews
        public ActionResult Index([Bind(Prefix ="id")]int ProductId)
        {
            var product = db.Products.Find(ProductId);
            if(product != null)
            return View(product);
            return HttpNotFound();
        }

        [HttpGet]
        public ActionResult Create(int ProductId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductReview ProductReview)
        {
            if (ModelState.IsValid)
            {
                db.Reviews.Add(ProductReview);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = ProductReview.ProductId });
            }
            return View(ProductReview);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Reviews.Find(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ProductReview ProductReview)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ProductReview).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = ProductReview.ProductId });
            }
            return View(ProductReview);
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebAppTest/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppTest.Models;

namespace WebAppTest.Controllers
{
    public class ProductsController : Controller
    {
        private ProductDb db = new ProductDb();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return View("Notfound");
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return View("Notfound");
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppTest/Views/Home/Index.cshtml
@model IPagedList<WebAppTest.Models.Product>

@{
    ViewBag.Title = "Home Page";
}
<form method="get" action="@Url.Action("Index")" data-me-ajax="true" data-me-target="#productList">
        <input type="search" name="searchTerm" data-me-autocomplete="@Url.Action("Autocomplete")"/>
        <input type="submit" value="Szukaj po nazwie"/>
    </form>

@Html.Partial("_Products",Model)

WebAppTest/Views/Home/_Products.cshtml
@model IPagedList<WebAppTest.Models.Product>

<div id="productList">

    <div class="pagedList" data-me-target="#productList">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), PagedListRenderOptions.MinimalWithItemCountText)
    </div>

    @foreach (var item in Model)
    {
        <div>
            <h4>@item.Name</h4>
            <div><b>Opis:</b> @item.Description <b>Cena:</b> @item.Price</div>
            <hr />
        </div>
    }
</div>

WebAppTest/Views/ProductReviews/Create.cshtml
@model WebAppTest.Models.ProductReview

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductReview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebAppTest/Views/ProductReviews/Edit.cshtml
@model WebAppTest.Models.ProductReview

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductReview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebAppTest/Views/ProductReviews/Index.cshtml
@model WebAppTest.Models.Product

@{
    ViewBag.Title = "Index";
}

<h2>Reviews for @Model.Name</h2>

@Html.Partial("_Reviews", Model.Reviews)

<p>
    @Html.ActionLink("Create New", "Create",new { ProductId = Model.Id})
</p>

WebAppTest/Views/ProductReviews/_Reviews.cshtml
@model IEnumerable<WebAppTest.Models.ProductReview>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Review)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReviewerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Review)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReviewerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebAppTest/Views/Products/Create.cshtml
@model WebAppTest.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebAppTest/Views/Products/Delete.cshtml
@model WebAppTest.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebAppTest/Views/Products/Details.cshtml
@model WebAppTest.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebAppTest/Views/Products/Edit.cshtml
@model WebAppTest.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebAppTest/Views/Products/Index.cshtml
@model IEnumerable<WebAppTest.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Reviews", "Index","ProductReviews", new { id = item.Id }, null) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}
</table>

WebAppTest/Views/Products/Notfound.cshtml
@{
    ViewBag.Title = "Notfound";
}

<h2>Przykro nam nie znalezieono takiego produktu</h2>

WebAppTest/Views/Shared/DisplayTemplates/Boolean.cshtml
@model Boolean?
@Html.DevExpress().CheckBoxFor(m => m, s => {
    s.ReadOnly = true;
}).GetHtml()

WebAppTest/Views/Shared/EditorTemplates/Boolean.cshtml
@model Boolean?
@Html.DevExpress().CheckBoxFor(m => m).GetHtml()

WebAppTest/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?
@Html.DevExpress().DateEditFor(m => m).GetHtml()

WebAppTest/Views/Shared/EditorTemplates/Decimal.cshtml
@model Decimal?
@Html.DevExpress().SpinEditFor(m => m).GetHtml()

WebAppTest/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object

@Html.DevExpress().TextBoxFor(m => m).GetHtml()

WebAppTest/Views/Shared/EditorTemplates/MultilineText.cshtml
@model object
@Html.DevExpress().MemoFor(m => m, s => {
    s.Width = 170;
}).GetHtml()

WebAppTest/Views/Shared/EditorTemplates/Password.cshtml
@model object
@Html.DevExpress().TextBoxFor(m => m, s => {
    s.Properties.Password = true;
}).GetHtml()

WebAppTest/Views/Shared/EditorTemplates/String.cshtml
@model object
@{
    Type tModel = ViewData.ModelMetadata.ContainerType.GetProperty(ViewData.ModelMetadata.PropertyName).PropertyType;
}
@if(typeof(string).IsAssignableFrom(tModel)) {
    @Html.DevExpress().TextBoxFor(m => m).GetHtml();
}
else if(typeof(Enum).IsAssignableFrom(tModel)) {
    Html.DevExpress().ComboBoxFor(m => m, s => {
        s.Properties.Items.AddRange(Enum.GetValues(tModel));
        s.SelectedIndex = 0;
        s.Properties.DropDownStyle = DropDownStyle.DropDownList;
    }).GetHtml();
} 

WebAppTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8" />
    <title>DevExpress ASP.NET project</title>
    
    @Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }
    )
    @Html.DevExpress().GetScripts( 
        new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new Script { ExtensionSuite = ExtensionSuite.Editors }
    )
    <link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/jquery-ui.css")" rel="stylesheet" type="text/css"/>
    <link href="@Url.Content("~/Content/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="content-wrapper">
        <h1>Patrzacz Produktów</h1>
        <div>            
            <nav class="ui-menu">
                <ul>
                    <li class="ui-menu-item">@Html.ActionLink("Home","Index","Home")</li>
                    <li class="ui-menu-item">@Html.ActionLink("Products", "Index", "Products")</li>
                </ul>
                <hr/>
            </nav >
        </div>       
        <div class="main-content">

            @RenderBody()
        </div>

        <div class="footer">
            <p>&copy; @DateTime.Now.Year - DevExpress ASP.NET project copyright</p>
        </div>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/me.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
</body>
</html>